
@hostname = http://localhost:4000

get {{hostname}}/offers

###

post {{hostname}}/comments
Content-Type: application/json

{
  "text": "Test Comment",
  "rating": 0,
  "offerId": "65db2437134b5517a2840445",
  "authorId": "65db2437134b5517a2840442"
}

###

get {{hostname}}/offers/65db2437134b5517a2840445

###

get {{hostname}}/offers/65db2437134b5517a2840445/comments
