
@hostname = http://localhost:4000

get {{hostname}}/offers

###

post {{hostname}}/offers
Content-Type: application/json

{
  "title": "",
  "description": "",
  "postDate": "",
  "city": "",
  "photoPreview": "",
  "photos": "",
  "isPremium": "",
  "isFavorite": "",
  "rating": "",
  "type": "",
  "roomsCount": "",
  "guestsCount": "",
  "price": "",
  "options": "",
  "authorId": "",
  "location": ""
}

###

get {{hostname}}/offers/65db2437134b5517a2840441

###

post {{hostname}}/comments
Content-Type: application/json

{
  "text": "Test Comment",
  "rating": 0,
  "offerId": "65db2437134b5517a2840445",
  "authorId": "65db2437134b5517a2840442"
}

###

get {{hostname}}/offers/65db2437134b5517a2840445

###

get {{hostname}}/offers/65db2437134b5517a2840445/comments

###

## Отправить изображение

POST {{hostname}}/users/65db2437134b5517a2840442/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="kandinsky-download-1708522976061.png"
Content-Type: image/png

< C:\Users\pt1c\Desktop\kandinsky-download-1708522976061.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
